services:
  app:
    image: henrique/app-php:prod-nginx-php-fpm8.3.2
    container_name: app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.3.2-fpm-bullseye'
    volumes:
      - .:/var/www
    ports:
      - "${APP_PORT:-80}:80" #http
      - "443:443" #https
      - "9001:9001" #php-fpm
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - app-estacionamento
  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'app-mysql:/var/lib/mysql'
    networks:
      - app-estacionamento
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-ppassword'
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'app-redis:/data'
    networks:
      - app-estacionamento
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

volumes:
  app-mysql:
    driver: local
  app-redis:
    driver: local

networks:
  app-estacionamento:
    driver: bridge
